---

#  This is the name of the site as it'll appear in the address bar.
site_name: "AWS Cloud Practitioner"

# Brief site description.
site_description: "Study notes for aws cloud practitioner exam"

# Site author
site_author: "Nathon Fowlie"

# Display an "Edit on GitHub Enterprise" link at the top of each page.
edit_uri: "edit/master/docs/"

# Additional variables that can be embedded into the generated documentation. The
# markdownextra-data plugin also supports loading data from an external file.
extra:

  #################################################################################################
  # These variables are used by the "material" theme.

  # "Social" links displayed in the page footer.
  social:
    - name: GitHub
      link: https://github.com/nathonfowlie
      icon: fontawesome/brands/github

  # Enables GitHub Pages versioning, using the "mike" utility. Each published version will be put
  # in it's own sub-folder under /docs.
  version:
    provider: mike

extra_javascript:
  - js/extra.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - mdx_include:
      allow_remote: False
      base_path: docs
  # This has to be disabled, as the plugin appears to have a bug that causes mkdocs to throw an
  # exception when the page title contains a link.
  # - mdx_titlecase.mdx_titlecase
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: True
      clickable_checkbox: False
  - pymdownx.tilde
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home:
    - Overview: index.md
    - Identity & Access Management: iam.md
    - EC2: ec2.md
    - EBS: ebs.md
  - Resources: resources.md

plugins:
  - search:
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - macros

repo_name: GitHub

repo_url: https://github.com/nathonfowlie/education.aws.cloudpractitioner

theme:
  name: material
  palette:
    scheme: default
  icon:
    repo: fontawesome/brands/github-square
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
