---

name: Publish docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy MkDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

