---

name: Publish docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy MkDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          CUSTOM_DOMAIN: thedistinguished.engineer
          CONFIG_FILE: mkdocs.yml
          PERSONAL_TOKEN: ${{ PERSONAL_TOKEN }}

